<?php

$_helper = Mage::helper('mventory_tm/tm');

$_categories = $this->getCategories();
$_selectedCategories = $this->getSelectedCategories();

$_cols = $this->getColsNumber() - 1;

$_tmUrl = $this->getTmUrl();

?>

<div class="grid">
  <table id="tm_selected_categories" class="data" cellspacing="0">
    <colgroup>
      <col width='1' />

      <?php for ($n = 0; $n <= $_cols; ++$n): ?>
      <col />
      <?php endfor; ?>
    </colgroup>

    <tbody>
      <?php foreach ($_selectedCategories as $id): ?>
        <?php if (isset($_categories[$id])): ?>
        <tr onclick="window.tm_mouseclick(event)" onmouseover="window.tm_mouseover(event)" onmouseout="tm_mouseout(event)" class="pointer">
          <td class="checkbox a-center">
            <input type="checkbox" class="category-check" value="<?php echo $id; ?>" checked="checked" onclick="window.tm_second_checkbox(event)" />
            <input type="hidden" class="category-url" value="<?php echo $_tmUrl . $_categories[$id]['path']; ?>" />
          </td>

          <?php for ($n = 0; $n <= $_cols; ++$n): ?>
          <td <?php echo $n == $_cols ? 'class="last"' : '' ?>>
            <?php echo isset($_categories[$id]['name'][$n]) ? $_categories[$id]['name'][$n] : ''; ?>
          </td>
          <?php endfor; ?>
        </tr>

          <?php $attrs = $_helper->getAttributes($id); ?>

          <?php if ($attrs): ?>
          <tr class="category-attrs">
            <td><?php echo $this->__('Attributes'); ?>:</td>
            <td colspan=<?php echo $_cols + 1; ?> class="last">
            <?php foreach ($attrs as $attr): ?>
              <?php echo $attr['Name'] . ' (' . $attr['Type'] . '), '; ?>
            <?php endforeach; ?> 
            </td>
          </tr>
          <?php endif; ?>
        <?php endif; ?>
      <?php endforeach; ?>
    </tbody>
  </table>
</div>

<div class="grid">
  <table id="tm_categories" class="data" cellspacing="0">
    <colgroup>
      <col width='1' />

      <?php for ($n = 0; $n <= $_cols; ++$n): ?>
      <col />
      <?php endfor; ?>
    </colgroup>

    <thead>
      <tr class="filter">
        <th></th>
        <th colspan="<?php echo $_cols + 1; ?>">
          <div class="field-100">
            <input id="tm_filter" class="input-text no-changes" type="text" onkeyup="window.tm_filter()" />
          </div>
        </th>
      </tr>
    </thead>
    <tbody>

      <?php $i = 0; ?>

      <?php foreach ($_categories as $id => $category): ?>
      <?php
        $classes = ((++$i % 2 == 0) ? 'even' : 'odd') . ' pointer';

        $isSelected = in_array($id, $_selectedCategories);

        if ($isSelected)
          $classes .= ' selected-row';
      ?>
      <tr class="<?php echo $classes ?>" onclick="window.tm_mouseclick(event)" onmouseover="window.tm_mouseover(event)" onmouseout="tm_mouseout(event)">
        <td class="checkbox a-center">
          <input type="checkbox" class="category-check" value="<?php echo $id; ?>" <?php echo $isSelected ? 'checked="checked"' : ''; ?> onclick="window.tm_main_checkbox(event)" />
          <input type="hidden" class="category-url" value="<?php echo $_tmUrl . $category['path']; ?>" />
        </td>

        <?php for ($n = 0; $n <= $_cols; ++$n): ?>
        <td <?php echo $n == $_cols ? 'class="last"' : '' ?>>
          <?php echo isset($category['name'][$n]) ? $category['name'][$n] : ''; ?>
        </td>
        <?php endfor; ?>

      </tr>
      <?php endforeach; ?>

    </tbody>
  </table>
</div>
