<?php

$_categories = $this->getCategories();
$_selectedCategories = $this->getSelectedCategories();

$_cols = $this->getColsNumber() - 1;

?>

<div class="grid">
  <table id="tm_selected_categories" class="data" cellspacing="0">
    <colgroup>
      <col width='1' />
      <col />
    </colgroup>

    <tbody>
      <?php foreach ($_selectedCategories as $id): ?>
        <?php if (isset($_categories[$id])): ?>
        <tr onmouseover="window.tm_mouseover(event)" onmouseout="tm_mouseout(event)">
          <td class="checkbox a-center">
            <input type="checkbox" value="<?php echo $id; ?>" checked="checked" onclick="window.tm_second_checkbox(event)" />
          </td>

          <?php for ($n = 0; $n <= $_cols; ++$n): ?>
          <td><?php echo isset($_categories[$id][$n]) ? $_categories[$id][$n] : ''; ?></td>
          <?php endfor; ?>
        </tr>
        <?php endif; ?>
      <?php endforeach; ?>
    </tbody>
  </table>
</div>

<div class="grid">
  <table id="tm_categories" class="data" cellspacing="0">
    <colgroup>
      <col width='1' />
      <col />
    </colgroup>

    <thead>
      <tr class="filter">
        <th></th>
        <th colspan="<?php echo $_cols + 1; ?>">
          <div class="field-100">
            <input id="tm_filter" class="input-text no-changes" type="text" onkeyup="window.tm_filter()" />
          </div>
        </th>
      </tr>
    </thead>
    <tbody>

      <?php $i = 0; ?>

      <?php foreach ($_categories as $id => $names): ?>
      <?php
        $classes = (++$i % 2 == 0) ? 'even' : 'odd';

        $isSelected = in_array($id, $_selectedCategories);

        if ($isSelected)
          $classes .= ' selected-row';
      ?>
      <tr class="<?php echo $classes ?>" onmouseover="window.tm_mouseover(event)" onmouseout="tm_mouseout(event)">
        <td class="checkbox a-center">
          <input type="checkbox" value="<?php echo $id; ?>" <?php echo $isSelected ? 'checked="checked"' : ''; ?> onclick="window.tm_main_checkbox(event)" />
        </td>

        <?php for ($n = 0; $n <= $_cols; ++$n): ?>
        <td <?php echo $n == $_cols ? 'class="last"' : '' ?>>
          <?php echo isset($names[$n]) ? $names[$n] : ''; ?>
        </td>
        <?php endfor; ?>

      </tr>
      <?php endforeach; ?>

    </tbody>
  </table>
</div>
