<?php

$_attrs = $this->_getAttributes();
$_rules = $this->_getRules();

?>
<div id="tm-matching-rules">

<?php foreach ($_rules as $id => $_rule): ?>
  <?php $rule = $this->_prepareRule($_rule); ?>

  <div id="<?php echo $id; ?>" class="tm-matching-rule box clear">

    <div class="tm-remove-button">&#x274C;</div>

    <div class="tm-matching-rule-attrs">
      <div class="tm-inner">

      <?php foreach ($rule['attrs'] as $label => $values): ?>
        <div class="tm-matching-rule-attr clear">
          <div class="tm-matching-rule-attr-name"><?php echo $label; ?></div>
          <div class="tm-matching-rule-attr-value"><?php echo $values; ?></div>
        </div>
      <?php endforeach; ?>

      </div>
    </div>

    <div class="tm-matching-rule-category">
      <div class="tm-inner"><?php echo $rule['category']; ?></div>
    </div>

  </div>

<?php endforeach; ?>

  <div class="tm-matching-rule box clear tm-template">

    <div class="tm-matching-rule-attrs">
      <div class="tm-inner">

        <div class="tm-matching-rule-attr clear">
          <div class="tm-matching-rule-attr-name"></div>
          <div class="tm-matching-rule-attr-value"></div>
        </div>

      </div>
    </div>

    <div class="tm-matching-rule-category">
      <div class="tm-inner"></div>
    </div>

  </div>

</div>

<div id="tm-matching-new-rule-wrapper" class="box clear">
  <div id="tm-matching-new-rule" class="tm-matching-rule-attrs">
    <div class="tm-inner clear">
      <div class="tm-matching-new-attr tm-not-completed">

        <div class="tm-matching-new-attr-buttons">
          <a class="tm-remove-button">&#x274C;</a>
        </div>

        <div>
          <select class="tm-rule-attr">
            <?php foreach ($_attrs as $id => $attr): ?>
            <option value="<?php echo $id; ?>"><?php echo $attr['label']; ?></option>
            <?php endforeach; ?>
          </select>
        </div>

        <div class="tm-rule-arrow">&#8681;</div>

        <div>
          <select class="tm-rule-value" multiple="multiple"></select>
        </div>

      </div>
    </div>
  </div>

  <div class="tm-matching-rule-category">
    <div class="tm-inner">
      <?php echo $this->getChildHtml('categories_button'); ?>
      <span id="tm-matching-new-cat-name"></span>
    </div>
  </div>

  <div id="tm-matching-new-rule-buttons">
    <?php echo $this->getChildHtml('reset_rule_button'); ?>
    <?php echo $this->getChildHtml('save_rule_button'); ?>
  </div>
</div>

<div id="tm_categories_wrapper" class="grid"></div>

<script type="text/javascript">
//<![CDATA[

tm_attrs = <?php echo $this->_getAttributesJson(); ?>;
tm_urls = <?php echo $this->_getUrlsJson(); ?>;

//]]>
</script>
