<?php

$_product = $this->getProduct();

$_category = $this->getCategory();
$_categories = $this->getCategories();
$_preselectedCategories = $this->getPreselectedCategories();

$_multiple = count($_preselectedCategories) > 1;

$_cols = $this->getColsNumber() - 1;

$_productUrl = Mage::helper('mventory_tm/product')->getUrl($_product);
$_tmUrl = $this->getTmUrl();

$_allowBuyNow = $this->getAllowBuyNow();
$_addTmFees = $this->getAddTmFees();
$_shippingOptions = $this->getShippingOptions();
$_relist = $this->getRelist();
$_avoidWithdrawal = $this->getAvoidWithdrawal();
$_accounts = $this->getAccounts();

$_shippingRate = $this->getShippingRate();
$_tmFees = $this->getTmFees();
$_totalPrice = round($_product->getPrice() + $_shippingRate + $_tmFees, 2);

?>

<div class="hidden">
  <input type="hidden" value="0" name="product[tm_relist]" />
  <input type="hidden" value="0" name="product[tm_avoid_withdrawal]" />
  <input type="hidden" value="0" name="product[tm_allow_buy_now]" />
  <input type="hidden" value="0" name="product[tm_add_fees]" />
</div>

<p><?php echo $this->__('Product URL'); ?>: <a target="_blank" href="<?php echo $_productUrl; ?>"><?php echo $_productUrl; ?></a></p>

<div class="entry-edit">
  <fieldset>
    <label class="tm-option">
      <input type="checkbox" value="1" name="product[tm_relist]" <?php if ($_relist) echo 'checked="checked"'; ?> />
      <?php echo $this->__('Relist if not sold'); ?>
    </label>

    <label class="tm-option">
      <input type="checkbox" value="1" name="product[tm_avoid_withdrawal]" <?php if ($_avoidWithdrawal) echo 'checked="checked"'; ?> />
      <?php echo $this->__('Avoid withdrawal'); ?>
    </label>
  </fieldset>
</div>

<div class="entry-edit">
  <fieldset>
    <label class="tm-option">
      <?php echo $this->__('Account: '); ?>
      <select id="tm_account" class="select" name="product[tm_account_id]">
        <?php foreach ($_accounts as $acc): ?>
        <option value="<?php echo $acc['value']; ?>" <?php if ($acc['selected']) echo 'selected="selected"'; ?>><?php echo $acc['label'] ?></option>
        <?php endforeach; ?>
      </select>
    </label>

    <label class="tm-option">
      <?php echo $this->__('Shipping type: '); ?>
      <select class="select" name="product[tm_shipping_type]">
        <?php foreach ($_shippingOptions as $opt): ?>
        <option value="<?php echo $opt['value']; ?>" <?php if ($opt['selected']) echo 'selected="selected"'; ?>><?php echo $opt['label'] ?></option>
        <?php endforeach; ?>
      </select>
    </label>

    <label class="tm-option">
      <input type="checkbox" value="1" name="product[tm_allow_buy_now]" <?php if ($_allowBuyNow) echo 'checked="checked"'; ?> />
      <?php echo $this->__('Allow Buy Now'); ?>
    </label>

    <label class="tm-option">
      <input id="tm_add_fees" type="checkbox" value="1" name="product[tm_add_fees]" <?php if ($_addTmFees) echo 'checked="checked"'; ?> />
      <?php echo $this->__('Add TM fees'); ?>
    </label>
  </fieldset>
</div>

<p>
  Total price: $<span id="tm_total_price"><?php echo $_totalPrice; ?></span>
  <span id="tm_price_parts"<?php if (!($_shippingRate || $_tmFees)) echo ' style="display: none;"'; ?>>
    ($<?php echo round($_product->getPrice(), 2); ?>

    <span id="tm_shipping_rate_wrapper"<?php if (!$_shippingRate) echo ' style="display: none;"'; ?>>
      + $<span id="tm_shipping_rate"><?php echo round($_shippingRate, 2); ?></span> (shipping)
    </span>

    <span id="tm_fees_wrapper"<?php if (!$_tmFees) echo ' style="display: none;"'; ?>>
      + $<span id="tm_fees"><?php echo round($_tmFees, 2); ?></span> (commission)
    </span>)
  </span>
</p>

<table cellspacing="0" class="actions">
  <tbody>
    <tr>
      <td>
        <?php if ($_product->getTmListingId()): ?>
          <?php echo $this->__('Listing URL'); ?>:
          <?php $_listingUrl = Mage::helper('mventory_tm/tm')->getListingUrl($_product); ?>
        <a target="_blank" href="<?php echo $_listingUrl ?>">
          <?php echo $_listingUrl ?>
        </a>
        (<?php echo $this->__('ID'); ?>: <?php echo $_product->getTmListingId(); ?>  )
        <?php endif; ?>
      </td>
      <td class="tm-actions a-right">
      <?php
        if ($_product->getTmListingId()) {
          echo $this->getStatusButton();
          echo $this->getRemoveButton();
          echo $this->getUpdateButton();
        } else
          echo $this->getSubmitButton();
      ?>
      </td>
    </tr>
  </tbody>
</table>

<div class="grid">
  <table id="tm_selected_categories" class="data" cellspacing="0">
    <colgroup>
      <col width='1' />

      <?php for ($n = 0; $n <= $_cols; ++$n): ?>
      <col />
      <?php endfor; ?>

      <col width='1' />
    </colgroup>

    <tbody>
      <tr id="tm_no_selected_message" class="even <?php echo count($_preselectedCategories) ? 'no-display' : ''; ?>">
        <td class="empty-text a-center last" colspan="<?php echo $_cols + 3; ?>">
          <?php echo $this->__('No category selected. Please, select category from the list below.'); ?>
        </td>
      </tr>
      <?php foreach ($_preselectedCategories as $id): ?>
        <?php if (isset($_categories[$id])): ?>
          <?php $_checked = $_category == $id || !$_multiple; ?>

        <tr class="pointer">
          <td class="checkbox">
            <input type="radio" class="category-check" name="product[tm_category]"  value="<?php echo $id; ?>" <?php echo $_checked ? 'checked="checked"' : '' ?> />
          </td>

          <?php for ($n = 0; $n <= $_cols; ++$n): ?>
          <td>
            <?php echo isset($_categories[$id]['name'][$n]) ? $_categories[$id]['name'][$n] : ''; ?>
          </td>
          <?php endfor; ?>

          <td class="last">
            <a href="<?php echo $_tmUrl . $_categories[$id]['path']; ?>">
              <?php echo $this->__('View'); ?>
            </a>
          </td>
        </tr>

          <?php $attrs = $this->getPreparedAttributes($id); ?>

          <?php if ($attrs): ?>
          <tr class="category-attrs">
            <td><?php echo $this->__('Attributes'); ?>:</td>
            <td colspan=<?php echo $_cols + 2; ?> class="last">

            <?php if (count($attrs['existing'])): ?>
              <?php foreach ($attrs['existing'] as $attr): ?>
                <?php echo $attr['Name'] . ' (' . $attr['Type'] . '), '; ?>
              <?php endforeach; ?>

              <br />
            <?php endif; ?>

            <?php if (count($attrs['optional'])): ?>
              <?php echo $this->__('Optional'); ?>:

              <?php foreach ($attrs['optional'] as $attr): ?>
                <?php echo $attr['Name'] . ' (' . $attr['Type'] . '), '; ?>
              <?php endforeach; ?>

              <br />
            <?php endif; ?>

            <?php if (count($attrs['missing'])): ?>
              <?php echo $this->__('Missing'); ?>:

              <?php foreach ($attrs['missing'] as $attr): ?>
                <?php echo $attr['Name'] . ' (' . $attr['Type'] . '), '; ?>
              <?php endforeach; ?>
            <?php endif; ?>
            </td>
          </tr>
          <?php endif; ?>
        <?php endif; ?>
      <?php endforeach; ?>
    </tbody>
  </table>
</div>

<?php echo $this->getCategoriesButton(); ?>

<div id="tm_categories_wrapper" class="grid"></div>

<script type="text/javascript">
//<![CDATA[

tm_categories_for_product(<?php echo $this->getUrlTemplates() ?>);

jQuery(document).ready(function ($) {
  var tm_data = <?php echo Zend_Json::encode($this->prepareDataForJs()) ?>;
  var limit = <?php echo MVentory_Tm_Model_Connector::TITLE_MAX_LENGTH; ?>;

  var $options = $('#product_info_tabs_tm_content')
                   .find('.tm-option')
                   .children()
                   .filter(':input');

  $('#product_edit_form').on('submit', function () {
    var name = $(this).find('input[name="product[name]"]').val();

    if (name.length <= limit)
      return;

    name = name.substring(0, limit - 3) + '...';

    var msg = 'Product\'s name exceeded the limit of '
              + limit
              + ' symbols.\n'
              + 'Please reduce its length or press OK to use '
              + 'following truncated name "'
              + name
              + '"'

    return confirm(msg);
  });

  $('#tm_account').on('change', function () {
    var account = tm_data['accounts'][$(this).val()];

    for (var key in account) {
      var $option = $options.filter('[name*="' + key + '"]')

      if ($option.is(':checkbox'))
        $option.prop('checked', account[key] == true);
      else
        $option.val(account[key]);
    }

    tm_update_total_price(tm_data['product']['price'], account);
  });

  $('#tm_add_fees').on('change', function () {
    tm_update_total_price(tm_data['product']['price'],
                          tm_data['accounts'][$('#tm_account').val()]);
  })
});

//]]>
</script>
