<?php

$_product = $this->getProduct();

$_categories = $this->getCategories();
$_selectedCategories = $this->getSelectedCategories();

$_multiple = count($_selectedCategories) > 1;

$_cols = $this->getColsNumber() - 1;

$_productUrl = Mage::helper('mventory_tm/product')->getUrl($_product);
$_tmUrl = $this->getTmUrl();

$_allowBuyNow = $this->getAllowBuyNow();
$_addTmFees = $this->getAddTmFees();
$_shippingOptions = $this->getShippingOptions();
$_relist = $this->getRelist();
$_avoidWithdrawal = $this->getAvoidWithdrawal();
$_accounts = $this->getAccounts();

?>

<p><?php echo $this->__('Product URL'); ?>: <a target="_blank" href="<?php echo $_productUrl; ?>"><?php echo $_productUrl; ?></a></p>

<div class="entry-edit">
  <fieldset>
    <label class="tm-option">
      <input type="hidden" value="0" name="product[tm_relist]" />
      <input type="checkbox" value="1" name="product[tm_relist]" <?php if ($_relist) echo 'checked="checked"'; ?> />
      <?php echo $this->__('Relist if not sold'); ?>
    </label>

    <label class="tm-option">
      <input type="hidden" value="0" name="product[tm_avoid_withdrawal]" />
      <input type="checkbox" value="1" name="product[tm_avoid_withdrawal]" <?php if ($_avoidWithdrawal) echo 'checked="checked"'; ?> />
      <?php echo $this->__('Avoid withdrawal'); ?>
    </label>
  </fieldset>
</div>

<div class="entry-edit">
  <fieldset>
    <label class="tm-option">
      <?php echo $this->__('Account: '); ?>
      <select class="select" name="tm[account_id]">
        <?php foreach ($_accounts as $acc): ?>
        <option value="<?php echo $acc['value']; ?>" <?php if ($acc['selected']) echo 'selected="selected"'; ?>><?php echo $acc['label'] ?></option>
        <?php endforeach; ?>
      </select>
    </label>

    <label class="tm-option">
      <?php echo $this->__('Shipping type: '); ?>
      <select class="select" name="tm[shipping_type]">
        <?php foreach ($_shippingOptions as $opt): ?>
        <option value="<?php echo $opt['value']; ?>" <?php if ($opt['selected']) echo 'selected="selected"'; ?>><?php echo $opt['label'] ?></option>
        <?php endforeach; ?>
      </select>
    </label>

    <label class="tm-option">
      <input type="checkbox" value="1" name="tm[allow_buy_now]" <?php if ($_allowBuyNow) echo 'checked="checked"'; ?> />
      <?php echo $this->__('Allow Buy Now'); ?>
    </label>

    <label class="tm-option">
      <input type="checkbox" value="1" name="tm[add_tm_fees]" <?php if ($_addTmFees) echo 'checked="checked"'; ?> />
      <?php echo $this->__('Add TM fees'); ?>
    </label>
  </fieldset>
</div>

<table cellspacing="0" class="actions">
  <tbody>
    <tr>
      <td>
        <?php if ($_product->getTmListingId()): ?>
          <?php echo $this->__('Listing URL'); ?>:
          <?php $_listingUrl = Mage::helper('mventory_tm/tm')->getListingUrl($_product); ?>
        <a target="_blank" href="<?php echo $_listingUrl ?>">
          <?php echo $_listingUrl ?>
        </a>
        (<?php echo $this->__('ID'); ?>: <?php echo $_product->getTmListingId(); ?>  )
        <?php endif; ?>
      </td>
      <td class="tm-actions a-right">
      <?php
        if ($_product->getTmListingId()) {
          echo $this->getStatusButton();
          echo $this->getRemoveButton();
        } else
          echo $this->getSubmitButton();
      ?>
      </td>
    </tr>
  </tbody>
</table>

<div class="grid">
  <table id="tm_selected_categories" class="data" cellspacing="0">
    <colgroup>
      <col width='1' />

      <?php for ($n = 0; $n <= $_cols; ++$n): ?>
      <col />
      <?php endfor; ?>
    </colgroup>

    <tbody>
      <tr id="tm_no_selected_message" class="even <?php echo count($_selectedCategories) ? 'no-display' : ''; ?>">
        <td class="empty-text a-center last" colspan="10">
          <?php echo $this->__('No category selected. Please, select category from the list below.'); ?>
        </td>
      </tr>
      <?php foreach ($_selectedCategories as $id): ?>
        <?php if (isset($_categories[$id])): ?>
        <tr class="pointer">
          <td class="checkbox">
            <input type="radio" class="category-check" name="tm[category]"  value="<?php echo $id; ?>" <?php echo !$_multiple ? 'checked="checked"' : '' ?> />
            <input type="hidden" class="category-url" value="<?php echo $_tmUrl . $_categories[$id]['path']; ?>" />
          </td>

          <?php for ($n = 0; $n <= $_cols; ++$n): ?>
          <td <?php echo $n == $_cols ? 'class="last"' : '' ?>>
            <?php echo isset($_categories[$id]['name'][$n]) ? $_categories[$id]['name'][$n] : ''; ?>
          </td>
          <?php endfor; ?>
        </tr>

          <?php $attrs = $this->getPreparedAttributes($id); ?>

          <?php if ($attrs): ?>
          <tr class="category-attrs">
            <td><?php echo $this->__('Attributes'); ?>:</td>
            <td colspan=<?php echo $_cols + 1; ?> class="last">

            <?php if (count($attrs['existing'])): ?>
              <?php foreach ($attrs['existing'] as $attr): ?>
                <?php echo $attr['Name'] . ' (' . $attr['Type'] . '), '; ?>
              <?php endforeach; ?>

              <br />
            <?php endif; ?>

            <?php if (count($attrs['optional'])): ?>
              <?php echo $this->__('Optional'); ?>:

              <?php foreach ($attrs['optional'] as $attr): ?>
                <?php echo $attr['Name'] . ' (' . $attr['Type'] . '), '; ?>
              <?php endforeach; ?>

              <br />
            <?php endif; ?>

            <?php if (count($attrs['missing'])): ?>
              <?php echo $this->__('Missing'); ?>:

              <?php foreach ($attrs['missing'] as $attr): ?>
                <?php echo $attr['Name'] . ' (' . $attr['Type'] . '), '; ?>
              <?php endforeach; ?>
            <?php endif; ?>
            </td>
          </tr>
          <?php endif; ?>
        <?php endif; ?>
      <?php endforeach; ?>
    </tbody>
  </table>
</div>

<?php echo $this->getCategoriesButton(); ?>

<div id="tm_categories_wrapper" class="grid"></div>

<script type="text/javascript">
//<![CDATA[

tm_categories_for_product(<?php echo $this->getUrlTemplates() ?>);

//]]>
</script>
