<?php

/**
 * MVentory
 *
 * @category design
 * @package  default_default
 * @author   MVentory <???@mventory.com>
 */

?>

<?php

$_categories = $this->getCategories();
$_selectedCategories = $this->getSelectedCategories();

$_tmUrl = $this->getTmUrl();

$_cols = $this->getColsNumber() - 1;

?>

<table id="tm_categories" class="data" cellspacing="0">
  <colgroup>
    <col width='1' />

    <?php for ($n = 0; $n <= $_cols; ++$n): ?>
    <col />
    <?php endfor; ?>

    <col width='1' />
  </colgroup>

  <thead>
    <tr class="filter">
      <th></th>
      <th colspan="<?php echo $_cols + 2; ?>">
        <div class="field-100">
          <input id="tm_filter" class="input-text no-changes" type="text" />
        </div>
      </th>
    </tr>
  </thead>
  <tbody>

    <?php $i = 0; ?>

    <?php foreach ($_categories as $id => $category): ?>
    <?php
      $classes = ((++$i % 2 == 0) ? 'even' : 'odd') . ' pointer';

      $isSelected = in_array($id, $_selectedCategories);

      if ($isSelected)
        $classes .= ' selected-row';
    ?>
    <tr class="<?php echo $classes ?>">
      <td class="checkbox">
        <input type="checkbox" class="category-check" value="<?php echo $id; ?>" <?php echo $isSelected ? 'checked="checked"' : ''; ?> />
      </td>

      <?php for ($n = 0; $n <= $_cols; ++$n): ?>
      <td>
        <?php echo isset($category['name'][$n]) ? $category['name'][$n] : ''; ?>
      </td>
      <?php endfor; ?>

      <td class="last">
        <a href="<?php echo $_tmUrl . $category['path']; ?>">
          <?php echo $this->__('View'); ?>
        </a>
      </td>
    </tr>
    <?php endforeach; ?>

  </tbody>
</table>
