<?php

/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Creative Commons License BY-NC-ND.
 * NonCommercial — You may not use the material for commercial purposes.
 * NoDerivatives — If you remix, transform, or build upon the material,
 * you may not distribute the modified material.
 * See the full license at http://creativecommons.org/licenses/by-nc-nd/4.0/
 *
 * See http://mventory.com/legal/licensing/ for other licensing options.
 *
 * @package MVentory/TradeMe
 * @copyright Copyright (c) 2014 mVentory Ltd. (http://mventory.com)
 * @license http://creativecommons.org/licenses/by-nc-nd/4.0/
 */

/**
 * TradeMe categories table
 *
 * @package MVentory/TradeMe
 * @author Anatoly A. Kazantsev <anatoly@mventory.com>
 */

?>

<?php

$_categories = $this->getCategories();
$_selectedCategories = $this->getSelectedCategories();

$_type = $this->getInputType();

$_cols = $this->getColsNumber() - 1;

?>

<table id="trademe-categories" class="data" cellspacing="0">
  <colgroup>
    <col width='1' />

    <?php for ($n = 0; $n <= $_cols; ++$n): ?>
    <col />
    <?php endfor; ?>

    <col width='1' />
  </colgroup>

  <thead>
    <tr class="filter">
      <th></th>
      <th colspan="<?php echo $_cols + 2; ?>">
        <div class="field-100">
          <input id="trademe-categories-filter" class="input-text no-changes" type="text" />
        </div>
      </th>
    </tr>
  </thead>
  <tbody>

    <?php $i = 0; ?>

    <?php foreach ($_categories as $id => $category): ?>
    <?php
      $classes = ((++$i % 2 == 0) ? 'even' : 'odd') . ' pointer';

      $isSelected = in_array($id, $_selectedCategories);

      if ($isSelected)
        $classes .= ' trademe-state-selected';
    ?>
    <tr class="<?php echo $classes ?>">
      <td class="<?php echo $_type; ?>">
        <input type="<?php echo $_type; ?>" class="trademe-category-selector" <?php if ($_type == MVentory_TradeMe_Block_Categories::TYPE_RADIO) echo 'name="trademe_category"'; ?>value="<?php echo $id; ?>" />
      </td>

      <?php for ($n = 0; $n <= $_cols; ++$n): ?>
      <td><?php echo isset($category['name'][$n]) ? $category['name'][$n] : ''; ?></td>
      <?php endfor; ?>

      <td class="last">
        <a href="<?php echo MVentory_TradeMe_Block_Categories::URL . $category['path']; ?>">
          <?php echo $this->__('View'); ?>
        </a>
      </td>
    </tr>
    <?php endforeach; ?>

  </tbody>
</table>
