<?php

/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Creative Commons License BY-NC-ND.
 * NonCommercial — You may not use the material for commercial purposes.
 * NoDerivatives — If you remix, transform, or build upon the material,
 * you may not distribute the modified material.
 * See the full license at http://creativecommons.org/licenses/by-nc-nd/4.0/
 *
 * See http://mventory.com/legal/licensing/ for other licensing options.
 *
 * @package MVentory/TradeMe
 * @copyright Copyright (c) 2014 mVentory Ltd. (http://mventory.com)
 * @license http://creativecommons.org/licenses/by-nc-nd/4.0/
 * @author Anatoly A. Kazantsev <anatoly@mventory.com>
 */

$_rules = $this->_getRules();

?>

<div class="content-header">
  <table cellspacing="0">
    <tr>
      <td style="width:100%;">
        <h3 class="icon-head head-product-attribute-sets">
          <?php echo $this->__('TradeMe Categories Matching'); ?>
        </h3>
      </td>
    </tr>
  </table>
</div>

<div id="trademe-rules">

<?php foreach ($_rules as $id => $_rule): ?>
  <?php $rule = $this->_prepareRule($_rule); ?>

  <div id="<?php echo $id; ?>" class="trademe-rule box clear">

    <div class="trademe-rule-remove">&#x274C;</div>

    <div class="trademe-rule-attrs">
      <div class="trademe-inner">

      <?php if ($rule['default']): ?>
        <div class="trademe-rule-attr clear"><?php echo $this->__('Default rule'); ?></div>
      <?php else: ?>
        <?php foreach ($rule['attrs'] as $label => $values): ?>
          <div class="trademe-rule-attr clear">
            <div class="trademe-rule-attr-name"><?php echo $label; ?></div>
            <div class="trademe-rule-attr-value"><?php echo $values; ?></div>
          </div>
        <?php endforeach; ?>
      <?php endif; ?>

      </div>
    </div>

    <div class="trademe-rule-categories">
      <div class="trademe-inner">
        <div class="trademe-rule-category<?php if (!$rule['has_category']) echo ' trademe-state-no-category'; ?>"><?php echo $rule['category']; ?></div>
      </div>
    </div>

  </div>

<?php endforeach; ?>

  <div class="trademe-rule box clear trademe-rule-template">

    <div class="trademe-rule-remove">&#x274C;</div>

    <div class="trademe-rule-attrs">
      <div class="trademe-inner">

        <div class="trademe-rule-attr clear">
          <div class="trademe-rule-attr-name"></div>
          <div class="trademe-rule-attr-value"></div>
        </div>

      </div>
    </div>

    <div class="trademe-rule-categories">
      <div class="trademe-inner">
        <div class="trademe-rule-category"></div>
      </div>
    </div>

  </div>

</div>

<div class="box clear">
  <div id="trademe-rule-new" class="trademe-rule-attrs">
    <div class="trademe-inner clear">
      <div class="trademe-rule-new-attr trademe-state-not-completed">

        <div class="trademe-rule-new-attr-buttons">
          <a class="trademe-rule-remove">&#x274C;</a>
        </div>

        <div>
          <select class="trademe-rule-new-attr-name">
            <?php foreach ($this->_attrs as $id => $attr): ?>
            <option <?php if ($attr['used']) echo 'class="trademe-state-used-attr"'; ?> value="<?php echo $id; ?>"><?php echo $attr['label']; ?></option>
            <?php endforeach; ?>
          </select>
        </div>

        <div class="trademe-rule-arrow">&#8681;</div>

        <div>
          <select class="trademe-rule-new-attr-value" multiple="multiple"></select>
        </div>

      </div>
    </div>
  </div>

  <div class="trademe-rule-categories">
    <div class="trademe-inner">
      <div class="trademe-rule-category">
        <span id="trademe-rule-new-category"></span>
        <?php echo $this->getChildHtml('button_rule_categories'); ?>
        <?php echo $this->getChildHtml('button_rule_ignore'); ?>
      </div>
    </div>
  </div>

  <div id="trademe-rule-new-buttons">
    <?php echo $this->getChildHtml('button_rule_reset'); ?>
    <?php echo $this->getChildHtml('button_rule_save'); ?>
  </div>
</div>

<div id="trademe_wrapper_categories" class="grid"></div>

<script type="text/javascript">
//<![CDATA[

TRADEME_RULE_DEFAULT_ID = '<?php echo MVentory_TradeMe_Model_Matching::DEFAULT_RULE_ID; ?>';
TRADEME_RULE_DEFAULT_TITLE = '<?php echo $this->__('Default rule'); ?>';
TRADEME_DONT_LIST_TITLE = "<?php echo $this->__('Don\'t list on TradeMe'); ?>";

trademe_attrs = <?php echo $this->_getAttributesJson(); ?>;
trademe_urls = <?php echo $this->_getUrlsJson(); ?>;
trademe_used_categories = <?php echo $this->_getUsedCategories(); ?>;

//]]>
</script>
