<?php

/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Creative Commons License BY-NC-ND.
 * NonCommercial — You may not use the material for commercial purposes.
 * NoDerivatives — If you remix, transform, or build upon the material,
 * you may not distribute the modified material.
 * See the full license at http://creativecommons.org/licenses/by-nc-nd/4.0/
 *
 * See http://mventory.com/legal/licensing/ for other licensing options.
 *
 * @package MVentory/TradeMe
 * @copyright Copyright (c) 2014 mVentory Ltd. (http://mventory.com)
 * @license http://creativecommons.org/licenses/by-nc-nd/4.0/
 * @author Anatoly A. Kazantsev <anatoly@mventory.com>
 */

$_product = $this->getProduct();

$_categories = $this->getCategories();
$_preselectedCategories = $this->getPreselectedCategories();

$_cols = $this->getColsNumber() - 1;

$_productUrl = Mage::helper('mventory_tm/product')->getUrl($_product);

$_allowBuyNow = $this->getAllowBuyNow();
$_addFees = $this->getAddFees();
$_shippingType = $this->getShippingType();
$_pickup = $this->getPickup();
$_relist = $this->getRelist();
$_avoidWithdrawal = $this->getAvoidWithdrawal();
$_accounts = $this->getAccounts();

$_shippingRate = $this->getShippingRate();
$_fees = $this->getFees();
$_totalPrice = $_product->getPrice() + $_shippingRate + $_fees;

?>

<p><?php echo $this->__('Product URL'); ?>: <a target="_blank" href="<?php echo $_productUrl; ?>"><?php echo $_productUrl; ?></a></p>

<div class="entry-edit">
  <fieldset>
    <label class="trademe-option">
      <?php echo $this->getAttributeLabel('tm_relist'); ?>:
      <select class="select" name="product[tm_relist]">
        <?php foreach ($this->getAttributeOptions('tm_relist') as $value => $label): ?>
        <option value="<?php echo $value; ?>" <?php if ($value == $_relist) echo 'selected="selected"'; ?>><?php echo $label; ?></option>
        <?php endforeach; ?>
      </select>
    </label>

    <label class="trademe-option">
      <?php echo $this->getAttributeLabel('tm_avoid_withdrawal'); ?>:
      <select class="select" name="product[tm_avoid_withdrawal]">
        <?php foreach ($this->getAttributeOptions('tm_avoid_withdrawal') as $value => $label): ?>
        <option value="<?php echo $value; ?>" <?php if ($value == $_avoidWithdrawal) echo 'selected="selected"'; ?>><?php echo $label; ?></option>
        <?php endforeach; ?>
      </select>
    </label>

    <label class="trademe-option">
      <?php echo $this->getAttributeLabel('tm_allow_buy_now'); ?>:
      <select class="select" name="product[tm_allow_buy_now]">
        <?php foreach ($this->getAttributeOptions('tm_allow_buy_now') as $value => $label): ?>
        <option value="<?php echo $value; ?>" <?php if ($value == $_allowBuyNow) echo 'selected="selected"'; ?>><?php echo $label; ?></option>
        <?php endforeach; ?>
      </select>
    </label>

    <label class="trademe-option">
      <?php echo $this->getAttributeLabel('tm_add_fees'); ?>:
      <select id="trademe-tab-add-fees" class="select" name="product[tm_add_fees]">
        <?php foreach ($this->getAttributeOptions('tm_add_fees') as $value => $label): ?>
        <option value="<?php echo $value; ?>" <?php if ($value == $_addFees) echo 'selected="selected"'; ?>><?php echo $label; ?></option>
        <?php endforeach; ?>
      </select>
    </label>
  </fieldset>
</div>

<div class="entry-edit">
  <fieldset>
    <label class="trademe-option">
      <?php echo $this->__('Account: '); ?>
      <select id="tm_account" class="select" name="product[tm_account_id]">
        <?php foreach ($_accounts as $acc): ?>
        <option value="<?php echo $acc['value']; ?>" <?php if ($acc['selected']) echo 'selected="selected"'; ?>><?php echo $acc['label'] ?></option>
        <?php endforeach; ?>
      </select>
    </label>

    <label class="trademe-option">
      <?php echo $this->getAttributeLabel('tm_shipping_type'); ?>:
      <select id="trademe-tab-shipping-type" class="select" name="product[tm_shipping_type]">
        <?php foreach ($this->getAttributeOptions('tm_shipping_type') as $value => $label): ?>
        <option value="<?php echo $value; ?>" <?php if ($value == $_shippingType) echo 'selected="selected"'; ?>><?php echo $label; ?></option>
        <?php endforeach; ?>
      </select>
    </label>

    <label class="trademe-option">
      <?php echo $this->getAttributeLabel('tm_pickup'); ?>:
      <select class="select" name="product[tm_pickup]">
        <?php foreach ($this->getAttributeOptions('tm_pickup') as $value => $label): ?>
        <option value="<?php echo $value; ?>" <?php if ($value == $_pickup) echo 'selected="selected"'; ?>><?php echo $label; ?></option>
        <?php endforeach; ?>
      </select>
    </label>
  </fieldset>
</div>

<p>
  Total price: $<span id="trademe-total-price"><?php echo number_format($_totalPrice, 2); ?></span>
  <span id="trademe-price"<?php if (!($_shippingRate || $_fees)) echo ' style="display: none;"'; ?>>
    ($<?php echo number_format($_product->getPrice(), 2); ?>

    <span id="trademe-wrapper-shipping-rate"<?php if (!$_shippingRate) echo ' style="display: none;"'; ?>>
      + $<span id="trademe-shippingrate"><?php echo number_format($_shippingRate, 2); ?></span> (shipping)
    </span>

    <span id="trademe-wrapper-fees"<?php if (!$_fees) echo ' style="display: none;"'; ?>>
      + $<span id="trademe-fees"><?php echo number_format($_fees, 2); ?></span> (commission)
    </span>)
  </span>
</p>

<table cellspacing="0" class="actions">
  <tbody>
    <tr>
      <td>
        <?php if ($_product->getTmCurrentListingId()): ?>
          <?php echo $this->__('Listing URL'); ?>:
          <?php $_listingUrl = Mage::helper('trademe')->getListingUrl($_product); ?>
        <a target="_blank" href="<?php echo $_listingUrl ?>">
          <?php echo $_listingUrl ?>
        </a>
        (<?php echo $this->__('ID'); ?>: <?php echo $_product->getTmCurrentListingId(); ?>  )
        <?php endif; ?>
      </td>
      <td class="a-right">
      <?php
        if ($_product->getTmCurrentListingId()) {
          echo $this->getStatusButton();
          echo $this->getRemoveButton();
          echo $this->getUpdateButton();
        } else
          echo $this->getSubmitButton();
      ?>
      </td>
    </tr>
  </tbody>
</table>

<div class="grid">
  <table id="trademe-selected-categories" class="data" cellspacing="0">
    <colgroup>
      <col width='1' />

      <?php for ($n = 0; $n <= $_cols; ++$n): ?>
      <col />
      <?php endfor; ?>

      <col width='1' />
    </colgroup>

    <tbody>
      <tr id="trademe-message-no-selected" class="even <?php echo count($_preselectedCategories) ? 'no-display' : ''; ?>">
        <td class="empty-text a-center last" colspan="<?php echo $_cols + 3; ?>">
          <?php echo $this->__('No category selected. Please, select category from the list below.'); ?>
        </td>
      </tr>
      <?php foreach ($_preselectedCategories as $id): ?>
        <?php if (isset($_categories[$id])): ?>
          <?php $_checked = $this->getCategory() == $id; ?>

        <tr class="pointer">
          <td class="checkbox">
            <input type="radio" class="trademe-category-selector" name="trademe_category"  value="<?php echo $id; ?>" <?php echo $_checked ? 'checked="checked"' : '' ?> />
          </td>

          <?php for ($n = 0; $n <= $_cols; ++$n): ?>
          <td>
            <?php echo isset($_categories[$id]['name'][$n]) ? $_categories[$id]['name'][$n] : ''; ?>
          </td>
          <?php endfor; ?>

          <td class="last">
            <a href="<?php echo MVentory_TradeMe_Block_Tab::URL . $_categories[$id]['path']; ?>">
              <?php echo $this->__('View'); ?>
            </a>
          </td>
        </tr>

          <?php $attrs = $this->getPreparedAttributes($id); ?>

          <?php if ($attrs): ?>
          <tr class="trademe-category-attributes">
            <td><?php echo $this->__('Attributes'); ?>:</td>
            <td colspan=<?php echo $_cols + 2; ?> class="last">

            <?php if (count($attrs['existing'])): ?>
              <?php foreach ($attrs['existing'] as $attr): ?>
                <?php echo $attr['Name'] . ' (' . $attr['Type'] . '), '; ?>
              <?php endforeach; ?>

              <br />
            <?php endif; ?>

            <?php if (count($attrs['optional'])): ?>
              <?php echo $this->__('Optional'); ?>:

              <?php foreach ($attrs['optional'] as $attr): ?>
                <?php echo $attr['Name'] . ' (' . $attr['Type'] . '), '; ?>
              <?php endforeach; ?>

              <br />
            <?php endif; ?>

            <?php if (count($attrs['missing'])): ?>
              <?php echo $this->__('Missing'); ?>:

              <?php foreach ($attrs['missing'] as $attr): ?>
                <?php echo $attr['Name'] . ' (' . $attr['Type'] . '), '; ?>
              <?php endforeach; ?>
            <?php endif; ?>
            </td>
          </tr>
          <?php endif; ?>
        <?php endif; ?>
      <?php endforeach; ?>
    </tbody>
  </table>
</div>

<?php echo $this->getCategoriesButton(); ?>

<div id="trademe-categories-wrapper" class="grid"></div>

<script type="text/javascript">
//<![CDATA[

trademe_categories(<?php echo $this->getUrlTemplates() ?>);

jQuery(document).ready(function ($) {
  var data = <?php echo Zend_Json::encode($this->prepareDataForJs()) ?>;
  var limit = <?php echo MVentory_TradeMe_Model_Config::TITLE_MAX_LENGTH; ?>;

  var $options = $('#product_info_tabs_trademe_content')
                   .find('.trademe-option')
                   .children()
                   .filter(':input');

  $('#product_edit_form').on('submit', function () {
    var name = $(this).find('input[name="product[name]"]').val();

    if (name.length <= limit)
      return;

    name = name.substring(0, limit - 3) + '...';

    var msg = 'Product\'s name exceeded the limit of '
              + limit
              + ' symbols.\n'
              + 'Please reduce its length or press OK to use '
              + 'following truncated name "'
              + name
              + '"'

    return confirm(msg);
  });

  $('#tm_account').on('change', function () {
    var account = data['accounts'][$(this).val()];

    for (var key in account) {
      var $option = $options.filter('[name*="tm_' + key + '"]')

      //Ignore account options without corresponding fields on the page
      if ($option.length)
        $option.val(-1);
    }

    trademe_update_total_price(data['product']['price'], account);
  });

  $('#trademe-tab-add-fees, #trademe-tab-shipping-type').on(
    'change',
    function () {
      trademe_update_total_price(
        data['product']['price'],
        data['accounts'][$('#tm_account').val()]
      );
    }
  )
});

//]]>
</script>
