<?php

/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Creative Commons License BY-NC-ND.
 * NonCommercial — You may not use the material for commercial purposes.
 * NoDerivatives — If you remix, transform, or build upon the material,
 * you may not distribute the modified material.
 * See the full license at http://creativecommons.org/licenses/by-nc-nd/4.0/
 *
 * See http://mventory.com/legal/licensing/ for other licensing options.
 *
 * @package MVentory/API
 * @copyright Copyright (c) 2014 mVentory Ltd. (http://mventory.com)
 * @license http://creativecommons.org/licenses/by-nc-nd/4.0/
 */

/**
 * Admin dashboard Stock Info tab content
 *
 * @package MVentory/API
 */

?>
<div class="entry-edit">
  <div class="entry-edit-head"><h4>Total Stock Qty</h4></div>
  <fieldset class="a-center bold">
    <span class="nowrap" style="font-size:18px;"><span class="price"><?php echo $this->getTotalStockQty() ?></span><span style="font-size:14px; color:#686868;"></span></span>
  </fieldset>
</div>
<div class="entry-edit">
  <div class="entry-edit-head"><h4>Total Stock Value</h4></div>
  <fieldset class="a-center bold">
    <span class="nowrap" style="font-size:18px;"><span class="price"><?php echo $this->getTotalStockValue() ?></span><span style="font-size:14px; color:#686868;"></span></span>
  </fieldset>
</div>