<?php

/**
 * Store description template
 *
 * @see Mage_Catalog_Block_Product_View_Store
 */
?>

<?php $_info = $this->getInfo(); ?>

<?php if ($_info): ?>
  <h2><?php echo $_info['name']?></h2>

  <p class="store-url">
    <a href="<?php echo $_info['url']; ?>"><?php echo $_info['url']; ?></a>
  </p>

  <pre class="store-address"><?php echo $_info['address']; ?></pre>

  <p class="store-phone">Phone: <?php echo $_info['phone']; ?></p>
  <p class="store-email">
    E-mail: <a href="mailto:<?php echo $_info['email']; ?>">
              <?php echo $_info['email']; ?>
            </a>
  </p>

  <div id="store-map-canvas" class="store-map"></div>

  <?php $address = str_replace(array("\r\n", "\n", "\r"),
                               ' ',
                               trim($_info["address"])); ?>

  <script type="text/javascript">
  //<![CDATA[
    jQuery(document).ready(function ($) {
      var geocoder = new google.maps.Geocoder();

      geocoder.geocode(
        { 'address': '<?php echo $address ?>' },

        function(results, status) {
          if (status == google.maps.GeocoderStatus.OK) {
            var map_options = {
              zoom: 14,
              mapTypeId: google.maps.MapTypeId.ROADMAP
            }

            var map = new google.maps.Map(document.getElementById('store-map-canvas'),
                                    map_options);

            map.setCenter(results[0].geometry.location);

            var marker = new google.maps.Marker({
                           map: map,
                           position: results[0].geometry.location
                         });
          } else
            $('#store-map-canvas').remove();
            geocoder = null;
            map = null;
        });
      });
  //]]>
  </script>

<?php else: ?>
  <p>Seller details are not avaiable</p>
<?php endif; ?>
