<?php if (Mage::helper('mventory_tm')->isAdminLogged()) : ?>

<script type="text/javascript">
//<![CDATA[

_tm_image_editor_rotate_url = '<?php echo $this->getUrl('mventory_tm/image/rotate') ?>';
_tm_image_editor_remove_url = '<?php echo $this->getUrl('mventory_tm/image/remove') ?>';
_tm_image_editor_setmain_url = '<?php echo $this->getUrl('mventory_tm/image/setmain') ?>';

//]]>
</script>

<?php endif; ?>
