<?php
/**
 * Admin dashboard Stock Info tab content
 *
 * @category   design
 * @package    default_default
 * @author     MVentory <???@mventory.com>
 */
?>
<div class="entry-edit">
  <div class="entry-edit-head"><h4>Total Stock Qty</h4></div>
  <fieldset class="a-center bold">
    <span class="nowrap" style="font-size:18px;"><span class="price"><?php echo $this->getTotalStockQty() ?></span><span style="font-size:14px; color:#686868;"></span></span>
  </fieldset>
</div>
<div class="entry-edit">
  <div class="entry-edit-head"><h4>Total Stock Value</h4></div>
  <fieldset class="a-center bold">
    <span class="nowrap" style="font-size:18px;"><span class="price"><?php echo $this->getTotalStockValue() ?></span><span style="font-size:14px; color:#686868;"></span></span>
  </fieldset>
</div>